version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./containers/app/Dockerfile
    volumes:
      - ./app/:/docker_app/
    ports:
      - "3000:3000"
    container_name: app
    restart: always
  web:
    build:
      context: .
      dockerfile: ./containers/web/Dockerfile
    command: /bin/bash -c "envsubst '$$NGINX_BACKEND' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    environment:
      NGINX_BACKEND: app
    volumes:
      - ./containers/web/nginx.conf:/etc/nginx/nginx.conf
      - ./containers/web/default.conf.template:/etc/nginx/conf.d/default.conf.template
    ports:
      - "80:80"
    depends_on:
      - app
    container_name: web
    restart: always
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: friendship3312T
      MYSQL_USER: user
      MYSQL_PASSWORD: friendship3312T
      MYSQL_DATABASE: docker_app_development
    ports:
      - "3306:3306"
  
