default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: user
  password: friendship3312T
  host: db
  # host: <%= ENV['MYSQL_HOST'] %>
  # database: <%= ENV['MYSQL_DATABASE'] %>
  # username: <%= ENV['MYSQL_USER'] %>
  # password: <%= ENV['MYSQL_PASSWORD'] %>

development:
  <<: *default
  database: docker_app_development

test:
  <<: *default
    database: docker_test_development


production:
  <<: *default
