default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: password
  host: db
  # host: <%= ENV['MYSQL_HOST'] %>
  # database: <%= ENV['MYSQL_DATABASE'] %>
  # username: <%= ENV['MYSQL_USER'] %>
  # password: <%= ENV['MYSQL_PASSWORD'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
